package corba.server;


/**
* corbaserver/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

public final class ArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public ArrayHolder ()
  {
  }

  public ArrayHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.server.ArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.server.ArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.server.ArrayHelper.type ();
  }

}
