package corba.server;


/**
* corbaserver/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

public final class arrayHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public arrayHolder ()
  {
  }

  public arrayHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.server.arrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.server.arrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.server.arrayHelper.type ();
  }

}
