package corba.server;


/**
* corbaserver/CorbaPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:28 PM PDT
*/

public class CorbaPOATie extends CorbaPOA
{

  // Constructors

  public CorbaPOATie ( corba.server.CorbaOperations delegate ) {
      this._impl = delegate;
  }
  public CorbaPOATie ( corba.server.CorbaOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.server.CorbaOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.server.CorbaOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public double[] getAverage (corba.server.Payload payload)
  {
    return _impl.getAverage(payload);
  } // getAverage

  private corba.server.CorbaOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CorbaPOATie
