package corba.server;


/**
* corbaserver/CorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

public abstract class CorbaPOA extends org.omg.PortableServer.Servant
 implements corba.server.CorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAverage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corbaserver/Corba/getAverage
       {
         corba.server.Payload payload = corba.server.PayloadHelper.read (in);
         double $result[] = null;
         $result = this.getAverage (payload);
         out = $rh.createReply();
         corba.server.ArrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaserver/Corba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Corba _this() 
  {
    return CorbaHelper.narrow(
    super._this_object());
  }

  public Corba _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaPOA
