package corba.server;


/**
* corbaserver/CorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

public interface CorbaOperations 
{
  double[] getAverage (corba.server.Payload payload);
} // interface CorbaOperations
