package corba.server;


/**
* corbaserver/CorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

abstract public class CorbaHelper
{
  private static String  _id = "IDL:corbaserver/Corba:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.server.Corba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.server.Corba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.server.CorbaHelper.id (), "Corba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.server.Corba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.server.Corba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.server.Corba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.server.Corba)
      return (corba.server.Corba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.server._CorbaStub stub = new corba.server._CorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.server.Corba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.server.Corba)
      return (corba.server.Corba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.server._CorbaStub stub = new corba.server._CorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
