package corba.server;

/**
* corbaserver/CorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Saturday, October 15, 2011 7:12:31 PM PDT
*/

public final class CorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.server.Corba value = null;

  public CorbaHolder ()
  {
  }

  public CorbaHolder (corba.server.Corba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.server.CorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.server.CorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.server.CorbaHelper.type ();
  }

}
